"""Update add price history

Revision ID: 66276db28d72
Revises: fd2b13bead98
Create Date: 2024-11-16 00:35:37.454261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66276db28d72'
down_revision = 'fd2b13bead98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('balance')

    # ### end Alembic commands ###
