"""Update add trae into stock

Revision ID: e58d64ba117d
Revises: 72f99f3be080
Create Date: 2024-11-16 14:10:40.673894

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e58d64ba117d'
down_revision = '72f99f3be080'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.alter_column('open_price',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('high_price',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('low_price',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('close_price',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('volume',
               existing_type=mysql.BIGINT(),
               nullable=False)

    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.alter_column('change',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('volume',
               existing_type=mysql.BIGINT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.alter_column('volume',
               existing_type=mysql.BIGINT(),
               nullable=True)
        batch_op.alter_column('change',
               existing_type=mysql.FLOAT(),
               nullable=True)

    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.alter_column('volume',
               existing_type=mysql.BIGINT(),
               nullable=True)
        batch_op.alter_column('close_price',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('low_price',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('high_price',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('open_price',
               existing_type=mysql.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###
