"""Update add price history

Revision ID: fd2b13bead98
Revises: 3e204d9ca725
Create Date: 2024-11-16 00:15:30.931006

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fd2b13bead98'
down_revision = '3e204d9ca725'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('volume', sa.BigInteger(), nullable=True))
        batch_op.alter_column('change',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.drop_column('price_history')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_history', mysql.TEXT(), nullable=True))
        batch_op.alter_column('change',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.drop_column('volume')

    # ### end Alembic commands ###
